Added missing semicolon and Ok(()) to return Result<(), Error> instead of ()
This was giving an error during compilation:

error[E0308]: mismatched types
  --> programs/puppet_master/src/lib.rs:14:66
   |
14 |     pub fn pull_strings(ctx: Context<PullStrings>, data: u64) -> Result<()> {
   |            ------------                                          ^^^^^^^^^^ expected `Result<(), Error>`, found `()`
   |            |
   |            implicitly returns `()` as its body has no tail or `return` expression
   |
   = note:   expected enum `std::result::Result<(), anchor_lang::error::Error>`
           found unit type `()`